# Generated by Django 5.1.3 on 2024-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='button1_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='button2_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
